### ISSUE TITLE
[noetic] respeaker_ros failing to build armhf & armv8

### ISSUE THREAD

**Issue by sloretz** [jsk-ros-pkg/jsk_3rdparty#494]
* https://build.ros.org/view/Nbin_ufhf_uFhf/job/Nbin_ufhf_uFhf__respeaker_ros__ubuntu_focal_armhf__binary/99/console
* https://build.ros.org/view/Nbin_ufv8_uFv8/job/Nbin_ufv8_uFv8__respeaker_ros__ubuntu_focal_arm64__binary/

Seems the root of the problem is this line. It seems odd that there's something called `flac-linux-x86` on an ARM build.

```
objcopy: Unable to recognise the format of the input file `debian/ros-noetic-respeaker-ros/opt/ros/noetic/share/respeaker_ros/venv/lib/python3.8/site-packages/speech_recognition/flac-linux-x86'
```

Context:
```
23:20:35 	install -d debian/.debhelper/ros-noetic-respeaker-ros/dbgsym-root/usr/lib/debug/.build-id/51
23:20:35 	objcopy --only-keep-debug --compress-debug-sections debian/ros-noetic-respeaker-ros/opt/ros/noetic/share/respeaker_ros/venv/lib/python3.8/site-packages/speech_recognition/flac-linux-x86 debian/.debhelper/ros-noetic-respeaker-ros/dbgsym-root/usr/lib/debug/.build-id/51/fcc29644e1d696b6888cba74ab48ab5b0b809c.debug
23:20:35 objcopy: Unable to recognise the format of the input file `debian/ros-noetic-respeaker-ros/opt/ros/noetic/share/respeaker_ros/venv/lib/python3.8/site-packages/speech_recognition/flac-linux-x86'
23:20:35 dh_strip: error: objcopy --only-keep-debug --compress-debug-sections debian/ros-noetic-respeaker-ros/opt/ros/noetic/share/respeaker_ros/venv/lib/python3.8/site-packages/speech_recognition/flac-linux-x86 debian/.debhelper/ros-noetic-respeaker-ros/dbgsym-root/usr/lib/debug/.build-id/51/fcc29644e1d696b6888cba74ab48ab5b0b809c.debug returned exit code 1
23:20:35 dh_strip: error: Aborting due to earlier error
23:20:35 make: *** [debian/rules:27: binary] Error 25
23:20:35 dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
23:20:35 Traceback (most recent call last):
23:20:35   File "/tmp/ros_buildfarm/ros_buildfarm/binarydeb_job.py", line 149, in build_binarydeb
23:20:35     subprocess.check_call(cmd, cwd=source_dir, env=env)
23:20:35   File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
23:20:35     raise CalledProcessError(retcode, cmd)
23:20:35 subprocess.CalledProcessError: Command '['dpkg-buildpackage', '-b', '-us', '-uc']' returned non-zero exit status 2.
```

**Comment by mqcmd196** [comment]
`ros_speech_recognition` which uses `SpeechRecognition` pip package fails with the same error in aarch64.
```
objcopy: Unable to recognise the format of the input file `debian/ros-noetic-ros-speech-recognition/opt/ros/noetic/share/ros_speech_recognition/venv/lib/python3.8/site-packages/speech_recognition/flac-linux-x86'
dh_strip: error: objcopy --only-keep-debug --compress-debug-sections debian/ros-noetic-ros-speech-recognition/opt/ros/noetic/share/ros_speech_recognition/venv/lib/python3.8/site-packages/speech_recognition/flac-linux-x86 debian/.debhelper/ros-noetic-ros-speech-recognition/dbgsym-root/usr/lib/debug/.build-id/51/fcc29644e1d696b6888cba74ab48ab5b0b809c.debug returned exit code 1
dh_strip: error: Aborting due to earlier error
make: *** [debian/rules:27: binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
```
